# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  config.vm.box = "hashicorp/bionic64"

  config.trigger.before :up do |t|
    t.run = {path: "pre_check.sh"}
  end

  config.trigger.after :up do |t|
    t.info = "Create state.file"
    t.run_remote = {inline: "bash -c 'touch /home/vagrant/state.file'"}
  end

  config.trigger.before :halt, :destroy do |t|
    t.on_error = :continue
    t.info = "Remove state.file"
    t.run_remote = {inline: "bash -c 'rm -f /home/vagrant/state.file'"}
  end

end
