# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  config.vm.define "serverA" do |sa|
    sa.vm.box = "hashicorp/bionic64"
    sa.vm.network "private_network", ip: "192.168.56.10"
  end

  config.vm.define "serverB" do |sb|
    sb.vm.box = "hashicorp/bionic64"
    sb.vm.network "private_network", ip: "192.168.56.11"
  end

end
